// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB0uoUMsnNbXZ6H3eZFCi0qQNUTiJVNUg',
    appId: '1:54645173407:web:d93733bb4ee2e653c0c6aa',
    messagingSenderId: '54645173407',
    projectId: 'chateo-33e2b',
    authDomain: 'chateo-33e2b.firebaseapp.com',
    storageBucket: 'chateo-33e2b.firebasestorage.app',
    measurementId: 'G-FX20CT669L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdU4TVQPstJLaPiy86-zrTyCwgmW-6wz0',
    appId: '1:54645173407:android:df4834e70d36324cc0c6aa',
    messagingSenderId: '54645173407',
    projectId: 'chateo-33e2b',
    storageBucket: 'chateo-33e2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMnF2O_mZ2QtmHZ7eSxfue7zAfQE0Cz7o',
    appId: '1:54645173407:ios:6b4b10a23d0b4941c0c6aa',
    messagingSenderId: '54645173407',
    projectId: 'chateo-33e2b',
    storageBucket: 'chateo-33e2b.firebasestorage.app',
    iosBundleId: 'com.titos.chateo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMnF2O_mZ2QtmHZ7eSxfue7zAfQE0Cz7o',
    appId: '1:54645173407:ios:6b4b10a23d0b4941c0c6aa',
    messagingSenderId: '54645173407',
    projectId: 'chateo-33e2b',
    storageBucket: 'chateo-33e2b.firebasestorage.app',
    iosBundleId: 'com.titos.chateo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB0uoUMsnNbXZ6H3eZFCi0qQNUTiJVNUg',
    appId: '1:54645173407:web:c9cdd54caa5172ccc0c6aa',
    messagingSenderId: '54645173407',
    projectId: 'chateo-33e2b',
    authDomain: 'chateo-33e2b.firebaseapp.com',
    storageBucket: 'chateo-33e2b.firebasestorage.app',
    measurementId: 'G-GLY8280GXP',
  );
}
